# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IsingProcess <- function(nSample, graph, thresholds, beta, responses) {
    .Call(`_IsingOccu_IsingProcess`, nSample, graph, thresholds, beta, responses)
}

IsingSamplerCpp <- function(n, graph, thresholds, beta, nIter, responses, exact, constrain) {
    .Call(`_IsingOccu_IsingSamplerCpp`, n, graph, thresholds, beta, nIter, responses, exact, constrain)
}

H <- function(J, s, h) {
    .Call(`_IsingOccu_H`, J, s, h)
}

PartitionCpp <- function(graph, thr, beta, responses) {
    .Call(`_IsingOccu_PartitionCpp`, graph, thr, beta, responses)
}

IsingStateProbCpp <- function(Z, graph, thr, responses) {
    .Call(`_IsingOccu_IsingStateProbCpp`, Z, graph, thr, responses)
}

ColSumsarma <- function(A) {
    .Call(`_IsingOccu_ColSumsarma`, A)
}

Pdet_Ising_single_siteCpp <- function(det_thr_temp, Z_temp, dethis, sppmat_det, responses) {
    .Call(`_IsingOccu_Pdet_Ising_single_siteCpp`, det_thr_temp, Z_temp, dethis, sppmat_det, responses)
}

extract_thrCpp <- function(which_site, det_thr, nspp, nperiod, nsite) {
    .Call(`_IsingOccu_extract_thrCpp`, which_site, det_thr, nspp, nperiod, nsite)
}

Gibbs_Z_helperCpp <- function(Z_curr, scans, detmat, A, thr, sppmat_det, det_thr, nsite, responses) {
    .Call(`_IsingOccu_Gibbs_Z_helperCpp`, Z_curr, scans, detmat, A, thr, sppmat_det, det_thr, nsite, responses)
}

f <- function(Y, J, h) {
    .Call(`_IsingOccu_f`, Y, J, h)
}

Hvec <- function(s, Theta, N) {
    .Call(`_IsingOccu_Hvec`, s, Theta, N)
}

expvalues <- function(x) {
    .Call(`_IsingOccu_expvalues`, x)
}

vec2Thresh <- function(vec, P) {
    .Call(`_IsingOccu_vec2Thresh`, vec, P)
}

vec2Graph <- function(vec, P) {
    .Call(`_IsingOccu_vec2Graph`, vec, P)
}

Broderick2013 <- function(x, M, T, nIter, responses) {
    .Call(`_IsingOccu_Broderick2013`, x, M, T, nIter, responses)
}

